const data = [
  {
    id: 562,
    title: "APP上架AppStore洒泪记录",
    content: null,
    firstPicture:
      "https://images.pexels.com/photos/1441932/pexels-photo-1441932.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    flag: "原创",
    views: 228,
    appreciation: true,
    shareStatement: true,
    commentabled: true,
    published: true,
    recommend: false,
    createTime: "2021-03-12T13:10:18.000+0000",
    updateTime: "2021-03-12T13:10:18.000+0000",
    type: {
      id: 18,
      name: "踩坑记录",
      icon:'pit',
      blogssize: 0,
    },
    tags: [
      {
        id: 544,
        name: "uniapp",
        color: "#26b867",
        blogssize: 0,
      },
    ],
    user: {},
    comments: null,
    tagIds: null,
    commentssize: 11,
    description:
      "提交了6次，涉及到元数据、过期模块、功能不完整、第三方登录、支付等问题",
  },
  {
    id: 555,
    title: "uniapp使用5+plus对接微信授权登录",
    content: null,
    firstPicture:
      "https://images.pexels.com/photos/705425/pexels-photo-705425.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    flag: "原创",
    views: 117,
    appreciation: true,
    shareStatement: true,
    commentabled: true,
    published: true,
    recommend: false,
    createTime: "2021-02-25T15:27:01.000+0000",
    updateTime: "2021-02-25T15:27:01.000+0000",
    type: {
      id: 18,
      name: "踩坑记录",
      icon:'pit',
      blogssize: 0,
    },
    tags: [
      {
        id: 544,
        name: "uniapp",
        color: "#26b867",
        blogssize: 0,
      },
    ],
    user: {},
    comments: null,
    tagIds: null,
    commentssize: 8,
    description:
      "uniapp有统一的登录api,在HBuilderX中配置的参数云端打包后会保存在apk/ipa中，对于安全性要求高的开发者可能担心存在参数泄露的风险，可以采取5+plus将appSecret存放在服务端进行处理",
  },
  {
    id: 552,
    title: "阿里云免费ssl证书续签与https配置",
    content: null,
    firstPicture:
      "https://images.pexels.com/photos/3216084/pexels-photo-3216084.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    flag: "原创",
    views: 113,
    appreciation: true,
    shareStatement: true,
    commentabled: true,
    published: true,
    recommend: false,
    createTime: "2021-02-16T06:14:06.000+0000",
    updateTime: "2021-02-16T06:15:50.000+0000",
    type: {
      id: 16,
      name: "环境搭建",
      icon:'setup',
      blogssize: 0,
    },
    tags: [
      {
        id: 8,
        name: "服务器",
        color: "#f5753e",
        blogssize: 0,
      },
      {
        id: 128,
        name: "nginx",
        color: "#009900",
        blogssize: 0,
      },
      {
        id: 349,
        name: "https",
        color: "#dacbe2",
        blogssize: 0,
      },
    ],
    user: {},
    comments: null,
    tagIds: null,
    commentssize: 2,
    description: "前几天免费的ssl证书过期了,重新申请了一遍",
  },
  {
    id: 547,
    title: "uniapp资源在线升级热更新方案",
    content: null,
    firstPicture:
      "https://images.pexels.com/photos/2246476/pexels-photo-2246476.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    flag: "原创",
    views: 112,
    appreciation: true,
    shareStatement: true,
    commentabled: true,
    published: true,
    recommend: false,
    createTime: "2021-01-23T15:31:36.000+0000",
    updateTime: "2021-01-23T15:31:36.000+0000",
    type: {
      id: 18,
      name: "踩坑记录",
      icon:'pit',
      blogssize: 0,
    },
    tags: [
      {
        id: 544,
        name: "uniapp",
        color: "#26b867",
        blogssize: 0,
      },
    ],
    user: {},
    comments: null,
    tagIds: null,
    commentssize: 1,
    description: "Android的APP热更新流程&IOS跳转AppStore更新",
  },
  {
    id: 545,
    title: "uniapp使用原生导航栏的按钮手动触发页面的picker组件",
    content: null,
    firstPicture:
      "https://images.pexels.com/photos/890049/pexels-photo-890049.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    flag: "原创",
    views: 74,
    appreciation: true,
    shareStatement: true,
    commentabled: true,
    published: true,
    recommend: false,
    createTime: "2021-01-13T11:41:26.000+0000",
    updateTime: "2021-01-13T11:41:26.000+0000",
    type: {
      id: 18,
      name: "踩坑记录",
      icon:'pit',
      blogssize: 0,
    },
    tags: [
      {
        id: 126,
        name: "vue",
        color: "#35495E",
        blogssize: 0,
      },
      {
        id: 544,
        name: "uniapp",
        color: "#26b867",
        blogssize: 0,
      },
    ],
    user: {},
    comments: null,
    tagIds: null,
    commentssize: 1,
    description: "好家伙我直接好家伙",
  },
]
export default data